version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/workdir"
